### PR TITLE
Fix $ in sql str

### LINKED ISSUE #22: Handle '$' symbol in SQL string
It looks when we have `$` symbol (Scala string interpolation) our plugin doesn't work in a proper way. We should fix it

### PR DESCRIPTION
**Pull request by koljahuang**
- fix https://github.com/alexkon/pretty-sql-sbt-plugin/issues/22

### CODE REVIEW

File: src/test/scala/org/coins/sql/format/SQLFormatterPluginSpec.scala [hunk 1]
```diff
@@ -111,36 +111,40 @@ ${customLeftIndent}  FROM people"""
 
   /** `formatSQLInString` needs to implement the following features at the same time：
     *   1. none SQL string should not be affected.
-   *    2. SQL wrapped in single double quotes will not be formatted
+    *   2. SQL wrapped in single double quotes will not be formatted
     */
   "formatSQLInString" should "support situations as comments mentioned" in {
     val threeDoubleQuotes = "\"\"\""
```
Comment (alexkon) [inline src/test/scala/org/coins/sql/format/SQLFormatterPluginSpec.scala]: Please use more shorter version `threeDoubleQuotes` -> `tripleQuotes`

File: src/test/scala/org/coins/sql/format/SQLFormatterPluginSpec.scala [hunk 2]
```diff
@@ -111,36 +111,40 @@ ${customLeftIndent}  FROM people"""
...
+    val dollar_sign = "$"
```
Comment (alexkon) [inline src/test/scala/org/coins/sql/format/SQLFormatterPluginSpec.scala]: Please use camel case notation for variable name

File: src/test/scala/org/coins/sql/format/SQLFormatterPluginSpec.scala [hunk 3]
```diff
@@ -111,36 +111,40 @@ ${customLeftIndent}  FROM people"""
...
                             |    val sql1 = "  select * from user"
                             |    spark.sql("select * from user")
                             |    spark.sql($threeDoubleQuotes
                             |        |SELECT *
                             |        |  FROM user$threeDoubleQuotes.stripMargin)
-                            |    val sql2 = $threeDoubleQuotes-- this is a comment
-                            |                 |SELECT *
+                            |    val sql2 = s$threeDoubleQuotes-- this is a comment
+                            |                 |SELECT *,
+                            |                 |       $$date dt
```
Comment (alexkon) [inline src/test/scala/org/coins/sql/format/SQLFormatterPluginSpec.scala]: I suppose it should be like this: 
```
$$date -> ${dollar_sign}date
```

File: src/main/scala/org/coins/sql/format/SQLFormatterPlugin.scala [hunk 4]
```diff
@@ -45,15 +48,18 @@ object SQLFormatterPlugin extends AutoPlugin {
...
+    sqlPattern
+      .replaceAllIn(
+        replacedContent,
+        m => {
+          val sql = m.group(1)
+          val formattedSQL = formatSQLString(sql)
+          s"""\"\"\"$formattedSQL\"\"\".stripMargin"""
+        }
+      )
+      .replace(replacementMapping("$").toString, "$")
```
Comment (alexkon) [inline src/main/scala/org/coins/sql/format/SQLFormatterPlugin.scala]: I suggest it's better to use Dollar escape function and put it in the bottom of function `formatSQLString`:
```
  def escapeDollarSign(sql: String): String = {
    sql.replace("$", "\\$")
  }
```

**Review by alexkon — APPROVED** [review]
LGTM
